export const generateHealthSummary = async (user, records) => {
  const avgWeight =
    records.reduce((a, r) => a + Number(r.weight), 0) / records.length;

  const avgSugar =
    records.reduce((a, r) => a + Number(r.sugar), 0) / records.length;

  return `
    <h2>Patient Health Report</h2>
    <p><strong>Name:</strong> ${user.name}</p>
    <p><strong>Age:</strong> ${records[0].age}</p>

    <h3>Summary</h3>
    <ul>
      <li>Average Weight: ${avgWeight.toFixed(1)} kg</li>
      <li>Average Sugar: ${avgSugar.toFixed(1)} mg/dL</li>
    </ul>

    <p>Generated by RetireNow Platform</p>
  `;
};
